// run

// Copyright 2025 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
        "runtime/debug"
        "strings"
)

type Ignition int

func (e *Ignition) Start() {
        println(*e) // tested as line 10
}

type Engine struct {
        *Ignition
}
type Car struct {
        *Engine
}
type Starter interface {
        Start()
}

var gs Starter

func test73747PanicInStart() {
        // Test that there is no autogenerated inner frame for the wrapper
        defer expectPanic([]string{"main.(*Car).Start", "issue73747.go:17", "main.test73747PanicInStart"}, []string{"autogenerated"})
        e1 := Engine{nil}
        myCar := Car{Engine: &e1}
        gs = &myCar
        gs.Start()
}

func test73747PanicInWrapper() {
        // Expect autogenerated frame when panic starts there
        defer expectPanic([]string{"main.(*Car).Start", "<autogenerated>:1", "main.test73747PanicInWrapper"}, []string{"issue73747.go:17"})
        myCar := Car{Engine: nil}
        gs = &myCar
        gs.Start()
}

func callRecover() {
        if recover() != nil {
                println("recovered")
        }
}

type T int

func (*T) M() { callRecover() }

type S struct{ *T } // has a wrapper (*S).M wrapping (*T.M)
var v = S{new(T)}
var p = &S{new(T)}

func F(int)     { callRecover() } // call intermediate function
var fv = S.M    // using a function pointer to force using the wrapper
var fp = (*S).M // using a function pointer to force using the wrapper

func issue73916() {
        defer F(1)
        panic("73916")
}

func test73916() {
        // Expect the panic is recovered only here
        defer expectPanic([]string{"main.issue73916", "main.test73916"}, []string{})
        issue73916()
}

func issue73917() {
        defer fv(v)
        panic("73917")
}

func test73917() {
        // Expect the panic is recovered only here
        defer expectPanic([]string{"main.issue73917", "main.test73917"}, []string{})
        issue73917()
}

func issue73920() {
        defer fp(p)
        panic("73920")
}

func test73920() {
        // Expect the panic is recovered only here
        defer expectPanic([]string{"main.issue73920", "main.test73920"}, []string{})
        issue73920()
}

func main() {
        test73747PanicInStart()
        test73747PanicInWrapper()
        // test73916() // TODO
        // test73917() // TODO
        test73920()
}

func expectPanic(expected, unexpected []string) {
        if r := recover(); r != nil {
                stack := string(debug.Stack())
                for _, u := range unexpected {
                        if strings.Contains(stack, u) {
                                panic("unexpected in stack: " + u)
                        }
                }
                lines := strings.Split(stack, "\n")
                idx := -1
                for _, line := range lines {
                        if strings.Contains(line, "panic.go:") {
                                if idx != -1 {
                                        panic("too many panics")
                                }
                                idx++
                                continue
                        }
                        if idx >= 0 && strings.Contains(line, expected[idx]) {
                                idx++
                                if idx == len(expected) {
                                        break
                                }
                        }
                }
                if idx < len(expected) {
                        panic("expected in stack: " + expected[idx])
                }
        } else {
                panic("expected panic!")
        }
}
